server:
  port: 2500

spring:
  application:
    name: spring-cloud-alibaba-sentinel-consumer
  cloud:
    nacos:
      discovery:
        # Nacos 服务注册中心地址
        server-addr: 192.168.10.20:8001
        ip: 192.168.10.221
    sentinel:
      # 取消控制台懒加载
      eager: true
      transport:
        # 配置 Sentinel Dashboard 地址
        dashboard: localhost:8080
        # 默认端口 8719
        port: 8719
      # Sentinel 持久化配置
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.10.20:8001
            dataId: spring-cloud-alibaba-sentinel-consumer
            groupId: DEFAULT_GROUP
            data-type: json
            rule_type: flow

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 服务提供者路由
service-url:
  sentinel-producer-service: http://spring-cloud-alibaba-sentinel-producer

 # 开启 Feign 对 Sentinel 支持
feign:
  sentinel:
    enabled: true