server:
  port: 2900
# ==================================== stream =============================================
spring:
  application:
    name: spring-cloud-alibaba-seata-stock
  # ==================================== Nacos ==========================================
  cloud:
    nacos:
      discovery:
        # Nacos 服务注册中心地址
        server-addr: http://192.168.10.20:8001
        ip: 192.168.10.221
  # =================================== 数据源 ==========================================
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.16:3306/storage?useSSL=false&\
      characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: P@ssw0rd

# ================================= Seata Config ===========================================
# seata 客户端配置
seata:
  enabled: true
  application-id: seata-storage
  tx-service-group: storage_tx_group
  service:
    vgroup-mapping:
      storage_tx_group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: http://192.168.10.20:8001
      namespace: public
      group: DEFAULT_GROUP
      cluster: default

# ================================= Mybatis Plus ===========================================
mybatis-plus:
  # 指定加载Mapper.xml文件路径
  mapper-locations: classpath*:/mapper/**Mapper.xml
  # 指定扫描实体类的包路径
  type-aliases-package: cn.wickson.alibaba.cloud.seata.storage.model.entity
  # 开启自动驼峰命名规则
  configuration:
    map-underscore-to-camel-case: true